### ISSUE TITLE
ConsensusPage 개발

### ISSUE THREAD

**Issue by Phoebe125** [valueGa/valueGa_frontend#11]
## 💡 Feature Issue
ConsensusPage 전체적인 디자인, css 개발

## 🌿  Tasks
- [ ] 목표 주가 그래프
- [ ] 기업 검색 바
- [ ] Buy/Sell Tab 생성
- [ ] 각 Tab에 맞는 항목 리스트 추가
