### ISSUE TITLE
템플릿 생성시 종목, 템플릿 선택 리팩터링

### ISSUE THREAD

**Issue by KimRiun** [valueGa/valueGa_frontend#23]
## 💡 Feature Issue

템플릿 생성시 종목, 템플릿 선택 리팩터링

## 🌿  Tasks

- [ ] stock 이름도 함께 받을 수 있게 수정하기
- [ ] 종목 선택시 종목 리스트 보이는 부분 수정하기
- [ ] 템플릿 선택에 PC에서 선택하기 추가하기
