### ISSUE TITLE
개별 Consensus 페이지 개발 

### ISSUE THREAD

**Issue by kmj-99** [valueGa/valueGa_frontend#27]
## 💡 Feature Issue

개별 컨센서스 UI 개발

## 🌿  Tasks

- [x] 현재/목표 주가 및 컨센서스 비율 UI
- [x] 재무제표 UI
- [x] 주가 차트 UI
- [x] 유저 별 과거/현재 상승여력 리스트 UI
