### ISSUE TITLE
로그인/회원가입 기능 추가

### ISSUE THREAD

**Issue by kmj-99** [valueGa/valueGa_frontend#34]
## 💡 Feature Issue

UI에서 로그인/회원가입 API를 연동하여 로그인/회원가입 기능 완성

## 🌿  Tasks

- [x] 로그인 API 연동
- [x] 회원가입 API 연동
- [x] 전체 컨센서스 차트 API 연동
- [x] localstorage에 토큰 저장
- [x] 컨센서스 API 요청시 헤더에 토큰 추가
