### ISSUE TITLE
엑셀 library를 react-spread-sheet 로 변경하고 리팩터링

### ISSUE THREAD

**Issue by KimRiun** [valueGa/valueGa_frontend#40]
## 💡 Feature Issue

react-spread-sheet 적용 확인

## 🌿  Tasks

- [x] react-spread-sheet 적용 확인
- [x] 엑셀표 만들기
- [x] 수식 적용 input bar랑 엑셀 cell 실시간 변경 확인
- [x] 템플릿화, 저장 등 버튼 UI 만들기
- [x] 기타 css 수정
