### ISSUE TITLE
컨센서스 화면 전체적인 수정 작업

### ISSUE THREAD

**Issue by sdc05103** [valueGa/valueGa_frontend#61]
## 💡 Feature Issue

컨센서스 화면 수정

## 🌿  Tasks

1. 네비 바 
- [x] 검색 버튼 → 검색 추가 or 없애기
- [x] BUY, SELL에 상승여력에 컬러 넣기
- [ ] 검색 api 연결하기
