### ISSUE TITLE
벨류에이션 생성 화면에서 종목 선택 할 때 검색 API 연결하기

### ISSUE THREAD

**Issue by KimRiun** [valueGa/valueGa_frontend#63]
## 💡 Feature Issue

벨류에이션 생성 화면에서 종목 선택 할 때 검색 API 연결하기

## 🌿  Tasks

- [x] 검색 API 확인
- [x] 프론트에 검색 API 연결하기
- [x] 종목 선택 UI 수정하기
