### ISSUE TITLE
전체/개별 컨센서스 기능 및 UI 수정

### ISSUE THREAD

**Issue by kmj-99** [valueGa/valueGa_frontend#67]
## 💡 Feature Issue

전체/개별 컨센서스에서 미비된 기능및UI 수정

## 🌿  Tasks

- [x] 개별 컨센서스 페이지에서 재무제표 css 수정
- [x] 개별 컨센서스 재무데이터 css 수정
- [x] 전체/개별컨센서스 페이지 테스트
- [x] About Us 사진 수정 → GIF
- [x] ValueGa? 랑 Future of 등등 z-index 텍스트 수정
- [x] 네비 바 화면내 이동
- [x] login 후 logout으로 버튼 이름 수정
- [x] 로그인 후 메인 화면에 남아있도록
