### ISSUE TITLE
메인/전체/개별 페이지 버그 해결

### ISSUE THREAD

**Issue by kmj-99** [valueGa/valueGa_frontend#84]
## 💡 Feature Issue

메인/전체/개별 페이지 테스트 할 때 나온 버그 해결

## 🌿  Tasks

- [x] 종합 컨센서스에서 종목을 검색하여 개별 컨센선스로 이동시 에러
- [x] 메인 페이지에서 헤더에 ValueGa 배치 및 아이콘수정, Footer에 아이콘 수정
- [x] 종합 컨센서스에서 “목표주가”에 이상한 이미지 
- [x] 메인페이지에서 “Logout”클릭시 바로 전환이 안됨
- [x] 컨센선스 전체 화면에 더보기 커서 마우스 포인터 변환
- [x] 종합 컨센서스에서 “종목명”에서 상승여력 수치 제거
