### ISSUE TITLE
컨센서스 페이지 에러 수정

### ISSUE THREAD

**Issue by kmj-99** [valueGa/valueGa_frontend#93]
## 💡 Feature Issue

변수 이름 수정

## 🌿  Tasks

- [ ] About As -> About Us로 수정
- [ ] 개별컨센서스에서 "주" 단위 컴마 적용하기
- [ ] 상승여력 계산식 수정
